version: 1.0.{build}

# Ensure that PowerShell v5 is present
os:
  - "WMF 5"

# set the
environment:
  APPVEYOR_PS_GALLERY_API_KEY:
    secure: UODT6L1HnLkZSbTCa3iiNl0k4Zld+WOVrq1nbcdX0q8X8BFAiLNdi1OcisvJ05xl
  APPVEYOR_HCHK_API_KEY:
    secure: M0ckUYrnDo8J+MD4vHJH48kmP3m2wYvHm5wlYD4thgsbCCvCfOlB26efwIXv1jJA

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.204 -Force | Out-Null
      Install-Module Pester -MinimumVersion 4.0.2 -Scope CurrentUser -Force | Out-Null
      Install-Module psake -MinimumVersion 4.6.0 -Scope CurrentUser -Force | Out-Null
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force | Out-Null

# Any commit message that has 'skip ci' will not run
skip_commits:
  message: /updated (readme|doc).*|update (readme|doc).*s/

build_script:
  - ps: . .\build.ps1

test: false