# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Install pester to the test system 
install:
  - cinst pester -y

# I'm note sure why we do this!
build: false

test_script:
# Test with native PS version
  - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -Script .\Tests\PS.HealthCheck.Tests.ps1 -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
